#!/usr/bin/env bash
# TRUE AlphaZero loop: self-play generated by net-in-Rust (search > net) -> train net on its visit
# policies -> export npz -> next cycle's self-play uses the improved net. Parameterized by env so it
# runs for any deck/matchup (Abomasnow, Lucario, ...).
#   DECK=data/decks/lucario_praxel.csv OPP=data/decks/lucario_praxel.csv BC=data/bc_lucario/records.jsonl \
#   MPT=net/lucario.pt MNPZ=net/lucario.npz SP=data/selfplay_lucario CK=net/ckpt_lucario TAG=luc \
#   nohup bash scripts/az_rust_loop.sh 300 >/dev/null 2>&1 &
cd "$(dirname "$0")/.."
N="${1:-300}"; W="${W:-14}"
DECK="${DECK:-data/decks/abomasnow.csv}"
OPP="${OPP:-data/decks/mega_lucario.csv}"
BC="${BC:-data/bc/records.jsonl}"
MPT="${MPT:-net/model.pt}"; MNPZ="${MNPZ:-net/model.npz}"
SP="${SP:-data/selfplay_rust}"; CK="${CK:-net/ckpt_rust}"; TAG="${TAG:-abom}"
PROG="az_${TAG}_progress.log"; LOG="az_${TAG}.log"
mkdir -p "$CK" "$SP"
[ -f "$MNPZ" ] || ./scripts/run.sh -m train.export_npz "$MPT" "$MNPZ"
for c in $(seq 1 "$N"); do
  ts=$(date +%H:%M:%S)
  timeout 600 ./scripts/run.sh -m train.selfplay_rust --pv "$MNPZ" --deck_a "$DECK" --deck_b "$OPP" \
    --games 180 --budget 0.3 --workers "$W" --out "$SP/records.jsonl" >> "$LOG" 2>&1
  tail -n 40000 "$SP/records.jsonl" > "$SP/r.tmp" 2>/dev/null && mv "$SP/r.tmp" "$SP/records.jsonl"
  timeout 400 ./scripts/run.sh -m train.train_net --bc "$BC" --selfplay "$SP/records.jsonl" \
    --init "$MPT" --out "$MPT" --epochs 6 >> "$LOG" 2>&1
  ./scripts/run.sh -m train.export_npz "$MPT" "$MNPZ" >> "$LOG" 2>&1
  cp "$MNPZ" "$CK/model_r${c}.npz"
  echo "[$ts] ${TAG}-cycle $c done; selfplay=$(wc -l < "$SP/records.jsonl" 2>/dev/null)" >> "$PROG"
done
echo "AZ-${TAG} DONE" >> "$PROG"
